export const countriesAPI = [
  {code: '01', name: 'Thành phố Hà Nội'},
  {code: '79', name: 'Thành phố Hồ Chí Minh'},
  {code: '86', name: 'Thành phố Đà Nẵng'},
  {code: '48', name: 'Tỉnh An Giang'},
  {code: '44', name: 'Tỉnh Bà Rịa – Vũng Tàu'},
  {code: '53', name: 'Tỉnh Bạc Liêu'},
  {code: '52', name: 'Tỉnh Bắc Kạn'},
  {code: '67', name: 'Tỉnh Bắc Giang'},
  {code: '09', name: 'Tỉnh Bắc Ninh'},
  {code: '93', name: 'Tỉnh Bến Tre'},
  {code: '58', name: 'Tỉnh Bình Định'},
  {code: '57', name: 'Tỉnh Bình Dương'},
  {code: '50', name: 'Tỉnh Bình Phước'},
  {code: '51', name: 'Tỉnh Bình Thuận'},
  {code: '31', name: 'Tỉnh Cà Mau'},
  {code: '64', name: 'Tỉnh Đắk Lắk'},
  {code: '65', name: 'Tỉnh Đắk Nông'},
  {code: '66', name: 'Tỉnh Điện Biên'},
  {code: '27', name: 'Tỉnh Đồng Nai'},
  {code: '25', name: 'Tỉnh Đồng Tháp'},
  {code: '96', name: 'Tỉnh Gia Lai'},
  {code: '62', name: 'Tỉnh Hà Giang'},
  {code: '63', name: 'Tỉnh Hà Nam'},
  {code: '90', name: 'Tỉnh Hà Tĩnh'},
  {code: '68', name: 'Tỉnh Hải Dương'},
  {code: '72', name: 'Tỉnh Hậu Giang'},
  {code: '47', name: 'Tỉnh Kiên Giang'},
  {code: '71', name: 'Tỉnh Kon Tum'},
  {code: '35', name: 'Tỉnh Lâm Đồng'},
  {code: '69', name: 'Tỉnh Lạng Sơn'},
  {code: '29', name: 'Tỉnh Nghệ An'},
  {code: '30', name: 'Tỉnh Ninh Bình'},
  {code: '36', name: 'Tỉnh Quảng Bình'},
  {code: '58', name: 'Tỉnh Quảng Ngãi'},
];
